"""Application contract for the AI Execution Runtime."""

from __future__ import annotations

from typing import Any, Protocol


class IExecutionRuntime(Protocol):
    def start(self, request: dict[str, Any]) -> dict[str, Any]: ...

    def receive_response(
        self,
        session_id: str,
        provider_response: Any,
        metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...

    def get(self, session_id: str) -> dict[str, Any] | None: ...

    def summary(self, session_id: str) -> dict[str, Any] | None: ...

    def diagnostics(self, session_id: str) -> dict[str, Any] | None: ...

    def cancel(self, session_id: str, reason: str = "") -> dict[str, Any]: ...

    def retry(self, session_id: str, reason: str = "") -> dict[str, Any]: ...

    def resume(self, session_id: str, reason: str = "") -> dict[str, Any]: ...

    def timeout(self, session_id: str, reason: str = "") -> dict[str, Any]: ...

    def report_failure(self, session_id: str, failure: dict[str, Any]) -> dict[str, Any]: ...
