"""Human-reviewable Azure DevOps PR comment formatting."""

from __future__ import annotations

from typing import Any


def build_pr_comment(report: dict[str, Any]) -> str:
    acceptance = report.get("acceptanceCoverage") or {}
    lines = [
        "## HEI Pull Request Intelligence",
        "",
        f"**Status:** {report.get('status')}",
        f"**Summary:** {report.get('changeSummary')}",
        "",
        "### Coverage",
        f"- Acceptance coverage: {acceptance.get('score', 0)}%",
        f"- Missing criteria: {len(report.get('missingCriteria') or [])}",
        f"- Missing tests: {len(report.get('missingTests') or [])}",
        f"- Risk: {report.get('risk', {}).get('level', 'Needs Review')}",
    ]
    for title, values in (
        ("Blocking Findings", report.get("blockingFindings")),
        ("Warnings", report.get("warnings")),
        ("Reviewer Recommendations", report.get("reviewerRecommendations")),
    ):
        if values:
            lines.extend(["", f"### {title}", *[f"- {value}" for value in values]])
    lines.extend(["", "_Generated by HEI from the approved engineering plan and synchronized Azure DevOps context. Human review is required._"])
    return "\n".join(lines)
