"""Versioned HEI operational baseline profiles.

These records describe the capabilities HEI is prepared to use. They are not
live provider discovery and do not create provider adapters.
"""

from __future__ import annotations

from .models import MODEL_REGISTRY_VERSION, ModelProfile


MODEL_PROFILES: tuple[ModelProfile, ...] = (
    {
        "id": "gpt",
        "name": "GPT",
        "provider": "OpenAI",
        "contextWindow": 128000,
        "reasoning": True,
        "maxOutput": 32768,
        "toolSupport": True,
        "vision": True,
        "streaming": True,
        "temperatureSupport": True,
        "jsonSupport": True,
        "systemPromptSupport": True,
        "capabilityTags": ["planning", "reasoning", "execution", "qa", "vision", "tools", "structured-output"],
        "enabled": True,
        "registryVersion": MODEL_REGISTRY_VERSION,
    },
    {
        "id": "codex",
        "name": "Codex",
        "provider": "OpenAI",
        "contextWindow": 128000,
        "reasoning": True,
        "maxOutput": 32768,
        "toolSupport": True,
        "vision": True,
        "streaming": True,
        "temperatureSupport": False,
        "jsonSupport": True,
        "systemPromptSupport": True,
        "capabilityTags": ["coding", "repository", "execution", "validation", "tools"],
        "enabled": True,
        "registryVersion": MODEL_REGISTRY_VERSION,
    },
    {
        "id": "claude",
        "name": "Claude",
        "provider": "Anthropic",
        "contextWindow": 200000,
        "reasoning": True,
        "maxOutput": 8192,
        "toolSupport": True,
        "vision": True,
        "streaming": True,
        "temperatureSupport": True,
        "jsonSupport": True,
        "systemPromptSupport": True,
        "capabilityTags": ["planning", "reasoning", "coding", "review", "vision", "tools"],
        "enabled": True,
        "registryVersion": MODEL_REGISTRY_VERSION,
    },
    {
        "id": "gemini",
        "name": "Gemini",
        "provider": "Google",
        "contextWindow": 1000000,
        "reasoning": True,
        "maxOutput": 8192,
        "toolSupport": True,
        "vision": True,
        "streaming": True,
        "temperatureSupport": True,
        "jsonSupport": True,
        "systemPromptSupport": True,
        "capabilityTags": ["long-context", "reasoning", "vision", "repository", "tools", "structured-output"],
        "enabled": True,
        "registryVersion": MODEL_REGISTRY_VERSION,
    },
    {
        "id": "glm",
        "name": "GLM",
        "provider": "Zhipu AI",
        "contextWindow": 128000,
        "reasoning": True,
        "maxOutput": 8192,
        "toolSupport": True,
        "vision": False,
        "streaming": True,
        "temperatureSupport": True,
        "jsonSupport": True,
        "systemPromptSupport": True,
        "capabilityTags": ["reasoning", "planning", "coding", "tools", "structured-output"],
        "enabled": True,
        "registryVersion": MODEL_REGISTRY_VERSION,
    },
    {
        "id": "qwen",
        "name": "Qwen",
        "provider": "Alibaba Cloud",
        "contextWindow": 128000,
        "reasoning": True,
        "maxOutput": 8192,
        "toolSupport": True,
        "vision": True,
        "streaming": True,
        "temperatureSupport": True,
        "jsonSupport": True,
        "systemPromptSupport": True,
        "capabilityTags": ["reasoning", "coding", "vision", "tools", "structured-output"],
        "enabled": True,
        "registryVersion": MODEL_REGISTRY_VERSION,
    },
    {
        "id": "ollama",
        "name": "Ollama",
        "provider": "Local",
        "contextWindow": 8192,
        "reasoning": False,
        "maxOutput": 4096,
        "toolSupport": False,
        "vision": False,
        "streaming": True,
        "temperatureSupport": True,
        "jsonSupport": False,
        "systemPromptSupport": True,
        "capabilityTags": ["local", "private", "offline", "completion"],
        "enabled": True,
        "registryVersion": MODEL_REGISTRY_VERSION,
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "provider": "DeepSeek",
        "contextWindow": 128000,
        "reasoning": True,
        "maxOutput": 8192,
        "toolSupport": True,
        "vision": False,
        "streaming": True,
        "temperatureSupport": True,
        "jsonSupport": True,
        "systemPromptSupport": True,
        "capabilityTags": ["reasoning", "coding", "planning", "tools", "structured-output"],
        "enabled": True,
        "registryVersion": MODEL_REGISTRY_VERSION,
    },
    {
        "id": "phi",
        "name": "Phi",
        "provider": "Microsoft Azure",
        "contextWindow": 1200,
        "reasoning": True,
        "maxOutput": 300,
        "toolSupport": False,
        "vision": False,
        "streaming": True,
        "temperatureSupport": True,
        "jsonSupport": False,
        "systemPromptSupport": True,
        "capabilityTags": ["small-context", "reasoning", "planning", "private-deployment"],
        "enabled": True,
        "registryVersion": MODEL_REGISTRY_VERSION,
    },
)
