"""Business service and infrastructure contracts for Azure DevOps integration."""

from __future__ import annotations

from typing import Any, Protocol


class IAzureDevOpsCredentialProvider(Protocol):
    def authorization_headers(self, connection: Any, correlation_id: str = "") -> dict[str, str]: ...


class IAzureDevOpsClient(Protocol):
    def list_projects(self, *, cancellation=None) -> list[dict[str, Any]]: ...
    def get_project(self, project_id: str, *, cancellation=None) -> dict[str, Any]: ...
    def list_teams(self, project_id: str, *, cancellation=None) -> list[dict[str, Any]]: ...
    def list_iterations(self, project: str, *, cancellation=None) -> list[dict[str, Any]]: ...
    def query_work_items(self, project: str, wiql: str, *, cancellation=None) -> list[dict[str, Any]]: ...
    def get_work_item(self, project: str, work_item_id: int, *, cancellation=None) -> dict[str, Any]: ...
    def get_work_item_revisions(self, project: str, work_item_id: int, *, cancellation=None) -> list[dict[str, Any]]: ...
    def list_repositories(self, project: str, *, cancellation=None) -> list[dict[str, Any]]: ...
    def get_repository(self, project: str, repository_id: str, *, cancellation=None) -> dict[str, Any]: ...
    def list_pull_requests(self, project: str, repository_id: str = "", *, cancellation=None) -> list[dict[str, Any]]: ...
    def get_pull_request(self, project: str, repository_id: str, pull_request_id: int, *, cancellation=None) -> dict[str, Any]: ...
    def get_pull_request_commits(self, project: str, repository_id: str, pull_request_id: int, *, cancellation=None) -> list[dict[str, Any]]: ...
    def get_pull_request_work_items(self, project: str, repository_id: str, pull_request_id: int, *, cancellation=None) -> list[dict[str, Any]]: ...
    def get_pull_request_iterations(self, project: str, repository_id: str, pull_request_id: int, *, cancellation=None) -> list[dict[str, Any]]: ...
    def get_pull_request_iteration_changes(self, project: str, repository_id: str, pull_request_id: int, iteration_id: int, *, cancellation=None) -> list[dict[str, Any]]: ...
    def list_builds(self, project: str, *, cancellation=None) -> list[dict[str, Any]]: ...


class IAzureDevOpsClientFactory(Protocol):
    def create(self, connection: Any, *, correlation_id: str = "") -> IAzureDevOpsClient: ...


class IAzureDevOpsConnectionService(Protocol):
    def register(self, value: dict[str, Any], *, correlation_id: str = "") -> dict[str, Any]: ...
    def list(self) -> list[dict[str, Any]]: ...
    def get(self, connection_id: str) -> dict[str, Any] | None: ...
    def validate(self, connection_id: str, *, correlation_id: str = "") -> dict[str, Any]: ...
    def health(self, connection_id: str) -> dict[str, Any]: ...


class IAzureDevOpsProjectService(Protocol):
    def list_organizations(self, connection_id: str) -> list[dict[str, Any]]: ...
    def list_projects(self, connection_id: str, *, correlation_id: str = "", cancellation=None) -> list[dict[str, Any]]: ...
    def get_project(self, connection_id: str, project_id: str, *, correlation_id: str = "", cancellation=None) -> dict[str, Any]: ...
    def list_teams(self, connection_id: str, project_id: str, *, correlation_id: str = "", cancellation=None) -> list[dict[str, Any]]: ...


class IAzureDevOpsWorkItemService(Protocol):
    def query(self, connection_id: str, project: str, wiql: str, *, correlation_id: str = "", cancellation=None) -> list[dict[str, Any]]: ...
    def get_hierarchy(self, connection_id: str, project: str, work_item_id: int, *, correlation_id: str = "", cancellation=None) -> dict[str, Any]: ...
    def get_revisions(self, connection_id: str, project: str, work_item_id: int, *, correlation_id: str = "", cancellation=None) -> list[dict[str, Any]]: ...


class IAzureDevOpsRepositoryService(Protocol):
    def list_repositories(self, connection_id: str, project: str, *, correlation_id: str = "", cancellation=None) -> list[dict[str, Any]]: ...
    def get_repository(self, connection_id: str, project: str, repository_id: str, *, correlation_id: str = "", cancellation=None) -> dict[str, Any]: ...


class IAzureDevOpsPullRequestService(Protocol):
    def list_pull_requests(self, connection_id: str, project: str, repository_id: str = "", *, correlation_id: str = "", cancellation=None) -> list[dict[str, Any]]: ...
    def get_pull_request(self, connection_id: str, project: str, repository_id: str, pull_request_id: int, *, correlation_id: str = "", cancellation=None) -> dict[str, Any]: ...
    def get_pull_request_context(self, connection_id: str, project: str, repository_id: str, pull_request_id: int, *, correlation_id: str = "", cancellation=None) -> dict[str, Any]: ...
    def list_builds(self, connection_id: str, project: str, *, correlation_id: str = "", cancellation=None) -> list[dict[str, Any]]: ...


class IAzureDevOpsIterationService(Protocol):
    def list_iterations(self, connection_id: str, project: str, *, correlation_id: str = "", cancellation=None) -> list[dict[str, Any]]: ...
    def get_current_sprint(self, connection_id: str, project: str, *, correlation_id: str = "", cancellation=None) -> dict[str, Any] | None: ...


class IAzureDevOpsWebhookService(Protocol):
    def handle(self, connection_id: str, payload: dict[str, Any], *, correlation_id: str = "") -> dict[str, Any]: ...


class IAzureDevOpsSyncService(Protocol):
    def request_sync(self, connection_id: str, project_id: str, sync_type: str = "ManualSync", *, correlation_id: str = "") -> dict[str, Any]: ...
    def status(self, project_id: str) -> dict[str, Any]: ...
    def history(self, project_id: str, limit: int = 50) -> dict[str, Any]: ...
    def request_reconciliation(self, connection_id: str, project_id: str, *, correlation_id: str = "") -> dict[str, Any]: ...
    def receive_webhook(self, payload: dict[str, Any], *, correlation_id: str = "") -> dict[str, Any]: ...
