"""Structural interfaces for reusable engineering-fact services."""

from __future__ import annotations

from typing import Any, Protocol

from ..models import (
    ArchitectureSummary,
    AzureDevOpsSummary,
    DependencySummary,
    EngineeringContext,
    EngineeringMemorySummary,
    RepositorySummary,
)


class IRepositoryService(Protocol):
    def analyze_repository(self, requirement: dict[str, Any]) -> RepositorySummary: ...
    def get_repository_summary(self, requirement: dict[str, Any]) -> RepositorySummary: ...
    def find_relevant_modules(self, requirement: dict[str, Any]) -> list[str]: ...
    def find_relevant_files(self, requirement: dict[str, Any]) -> list[dict[str, Any]]: ...
    def find_technology_stack(self, requirement: dict[str, Any]) -> dict[str, list[str]]: ...


class IMarkdownService(Protocol):
    def index_markdown(self, documents: dict[str, str]) -> dict[str, Any]: ...
    def search_documentation(self, query: str, limit: int = 10) -> list[dict[str, Any]]: ...
    def get_architecture_summary(self) -> str: ...


class IArchitectureService(Protocol):
    def analyze_architecture(self, repository: RepositorySummary | dict[str, Any]) -> ArchitectureSummary: ...
    def get_architecture_context(self, repository: RepositorySummary | dict[str, Any]) -> dict[str, Any]: ...


class IDependencyService(Protocol):
    def analyze_dependencies(
        self, requirement: dict[str, Any], repository: RepositorySummary | dict[str, Any],
    ) -> DependencySummary: ...
    def find_affected_modules(
        self, requirement: dict[str, Any], repository: RepositorySummary | dict[str, Any],
    ) -> list[str]: ...


class IAzureDevOpsService(Protocol):
    def analyze_project(self, requirement: dict[str, Any]) -> AzureDevOpsSummary: ...
    def find_similar_stories(self, value: EngineeringContext | dict[str, Any]) -> list[dict[str, Any]]: ...
    def find_open_work(self, requirement: dict[str, Any]) -> list[dict[str, Any]]: ...


class ISimilarityService(Protocol):
    def find_similar_requirement(self, value: EngineeringContext | dict[str, Any]) -> list[dict[str, Any]]: ...
    def find_reusable_implementation(self, value: EngineeringContext | dict[str, Any]) -> list[dict[str, Any]]: ...


class IEngineeringMemoryService(Protocol):
    def search_memory(self, requirement: dict[str, Any]) -> EngineeringMemorySummary: ...
    def save_insight(self, insight: dict[str, Any]) -> dict[str, Any]: ...
    def find_lessons_learned(self, requirement: dict[str, Any]) -> list[dict[str, Any]]: ...


class IEngineeringDiscoveryService(Protocol):
    def build_report(
        self, value: EngineeringContext | dict[str, Any],
    ) -> dict[str, Any]: ...


class IContextBuilder(Protocol):
    def build_optimized_context(self, context: EngineeringContext | dict[str, Any]) -> dict[str, Any]: ...


class IIntelligenceOrchestrator(Protocol):
    def build_requirement_context(self, requirement: dict[str, Any], **kwargs: Any) -> dict[str, Any]: ...
    def build_planning_context(self, requirement: dict[str, Any], **kwargs: Any) -> dict[str, Any]: ...
    def build_execution_context(self, value: EngineeringContext | dict[str, Any], **kwargs: Any) -> dict[str, Any]: ...
    def build_validation_context(self, value: EngineeringContext | dict[str, Any], **kwargs: Any) -> dict[str, Any]: ...
