from __future__ import annotations

import os
import tempfile
import unittest
from unittest.mock import patch

from backend.project_intelligence import ProjectIntelligenceService, _project_phi_prompt, _project_phi_prompt_with_diagnostics


class HealthyPhiProvider:
    def __init__(self, parsed: dict | None = None) -> None:
        self.calls = 0
        self.parsed = parsed or {
            "business_goal": "Phi goal",
            "business_outcomes": ["Phi outcome"],
            "recommended_features": [{"title": "Phi Fault Monitoring", "description": "Generated by Phi."}],
        }

    def is_enabled(self) -> bool:
        return True

    def health_snapshot(self) -> dict:
        return {
            "deployment": "Phi-4",
            "health": "healthy",
            "last_success": "2026-06-20T00:00:00Z",
            "last_failure": None,
            "average_latency_ms": 1200,
            "consecutive_failures": 0,
        }

    def safe_config(self) -> dict:
        return {"configured": True, "deployment": "Phi-4", "deployment_health": "healthy"}

    def probe_json(self, *args, **kwargs) -> dict:
        self.calls += 1
        return {
            "status": "success",
            "http_status": 200,
            "elapsed_ms": 123,
            "raw_content": '{"ok":true}',
            "parsed_json": self.parsed,
        }


class FailingPhiProvider(HealthyPhiProvider):
    def probe_json(self, *args, **kwargs) -> dict:
        self.calls += 1
        return {
            "status": "timeout",
            "http_status": None,
            "elapsed_ms": 20000,
            "raw_content": "",
            "parsed_json": {},
            "failure_reason": "provider_timeout",
            "failure_message": "Azure Phi request timed out.",
            "parse_error": "TimeoutError",
        }


class RecordingPhiProvider(HealthyPhiProvider):
    def __init__(self, parsed: dict | None = None) -> None:
        super().__init__(parsed)
        self.system_prompt = ""
        self.user_prompt = ""

    def probe_json(self, system_prompt: str, user_prompt: str, **kwargs) -> dict:
        self.system_prompt = system_prompt
        self.user_prompt = user_prompt
        return super().probe_json(system_prompt, user_prompt, **kwargs)


class UnhealthyPhiProvider(HealthyPhiProvider):
    def health_snapshot(self) -> dict:
        return {
            "deployment": "Phi-4",
            "health": "unhealthy",
            "last_success": None,
            "last_failure": "2026-06-20T00:00:00Z",
            "average_latency_ms": 0,
            "consecutive_failures": 5,
        }


class ProjectIntelligenceTests(unittest.TestCase):
    def test_save_and_load_profile(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            saved = service.save_profile(
                {
                    "project_description": "Mobile commerce platform",
                    "applications": ["Mobile App", "Backend"],
                    "technology_stack": ["React", "FastAPI"],
                    "development_standards": {
                        "architecture_patterns": ["MVVM"],
                        "security_requirements": ["OAuth2"],
                        "testing_requirements": ["Code coverage >80%"],
                    },
                    "ui_guidelines": {"primary_color": "#0057D8", "accessibility_rules": ["WCAG AA"]},
                    "repository_sources": ["README.md"],
                }
            )

            loaded = service.get_profile()

        self.assertEqual(saved["project_description"], "Mobile commerce platform")
        self.assertEqual(loaded["applications"], [{"name": "Mobile App", "type": "Mobile"}, {"name": "Backend", "type": "Backend"}])
        self.assertEqual(loaded["technology_stack"]["frontend"], ["React"])
        self.assertEqual(loaded["technology_stack"]["backend"], ["FastAPI"])
        self.assertEqual(loaded["development_standards"]["architecture_patterns"], ["MVVM"])
        self.assertEqual(loaded["ui_guidelines"]["primary_color"], "#0057D8")
        self.assertEqual(loaded["repository_sources"], ["README.md"])
        self.assertEqual(loaded["knowledge_profile_preview"]["readiness"], "Intermediate")
        self.assertTrue(loaded["onboarding_completed"])

    def test_analyze_description_infers_preview_profile(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            analyzed = service.analyze_description("iOS and Android mobile commerce app with backend APIs, checkout, payment and order analytics.")

        self.assertEqual(analyzed["knowledge_profile_preview"]["domain"], "E-commerce")
        self.assertIn({"name": "Mobile App", "type": "Mobile"}, analyzed["applications"])
        self.assertIn({"name": "Backend", "type": "Backend"}, analyzed["applications"])
        self.assertIn({"name": "Analytics", "type": "Analytics"}, analyzed["applications"])
        self.assertEqual(analyzed["domain"], "E-commerce")
        self.assertEqual(analyzed["project_type"], "Multi-System Platform")
        self.assertEqual(analyzed["knowledge_profile_preview"]["repository_status"], "Repository README scan coming next.")

    def test_generate_story_prompts_returns_ui_dev_and_qa(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            prompts = service.generate_story_prompts(
                {
                    "title": "Checkout with saved card",
                    "description": "As a customer, I want to pay with a saved card.",
                    "acceptance_criteria": ["Saved cards can be selected during checkout."],
                },
                {
                    "project_name": "Commerce App",
                    "domain": "Retail",
                    "project_type": "Mobile Application",
                    "project_description": "Mobile commerce platform",
                    "applications": [{"name": "Mobile App", "type": "Mobile"}, {"name": "Backend", "type": "Backend"}],
                    "technology_stack": {"mobile": ["Kotlin"], "backend": ["FastAPI"]},
                    "development_standards": {"architecture_patterns": ["MVVM"], "security_requirements": ["OAuth2"]},
                    "ui_guidelines": {"component_library": "Design System"},
                    "repository_sources": ["README.md"],
                },
            )

        self.assertIn("UI Prompt", prompts["ui_prompt"])
        self.assertIn("Dev Prompt", prompts["dev_prompt"])
        self.assertIn("QA Prompt", prompts["qa_prompt"])
        self.assertIn("Saved cards can be selected", prompts["qa_prompt"])
        self.assertIn("Project Name: Commerce App", prompts["dev_prompt"])
        self.assertIn("Domain: Retail", prompts["dev_prompt"])
        self.assertIn("Development Standards: MVVM; OAuth2", prompts["dev_prompt"])

    def test_analyze_readme_updates_knowledge_registry_and_prompts(self) -> None:
        readme = """
# Smart Meter Platform
Smart meter operations platform for mobile field work, backend APIs, and analytics.

## Modules
- Meter Inventory
- Outage Alerts
- Billing Sync

## Flows
- Meter onboarding
- Field inspection
- Consumption analytics

## Architecture
- Mobile app uses MVVM.
- Backend APIs use repository pattern.
- Events publish meter readings to analytics.
"""
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            profile = service.analyze_readme(
                readme,
                {"id": "repo-1", "name": "meter-platform", "branch": "main", "readme_path": "/README.md"},
                {"project_description": "Smart meter project", "technology_stack": {"mobile": ["Kotlin"], "backend": ["FastAPI"]}},
            )
            prompts = service.generate_story_prompts({"title": "Meter onboarding"}, profile)

        self.assertEqual(profile["repository_connection"]["status"], "README analyzed")
        self.assertIn("Meter Inventory", profile["knowledge_registry"]["modules"])
        self.assertIn("Meter onboarding", profile["knowledge_registry"]["flows"])
        self.assertIn("Detected Modules: Meter Inventory", prompts["dev_prompt"])
        self.assertIn("Detected Flows: Meter onboarding", prompts["dev_prompt"])

    def test_repository_document_analysis_populates_registry(self) -> None:
        documents = {
            "modules.md": """
# Modules
- Fault Monitoring
- Telemetry
- Event Repository
""",
            "flows.md": """
# Flows
- Fault Event Review
- Fault Event Timeline
- Device Telemetry Review
""",
            "architecture.md": """
# Architecture
- Events publish telemetry to the operations API.
- Mobile app uses MVVM.

# Components
- Fault Detail Screen
- Event Timeline
""",
            "coding-standards.md": """
# Coding Standards
- Repository Pattern
- Unit tests required
""",
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            profile = service.analyze_repository_documents(
                documents,
                {"repository_id": "repo-1", "repository_name": "linedefender", "branch": "main"},
                {"project_description": "LineDefender fault monitoring platform."},
            )

        self.assertEqual(profile["repository_status"], "analyzed")
        self.assertIn("Fault Monitoring", profile["knowledge_registry"]["modules"])
        self.assertIn("Fault Event Review", profile["knowledge_registry"]["flows"])
        self.assertIn("Events publish telemetry to the operations API.", profile["knowledge_registry"]["architecture_notes"])
        self.assertIn("Fault Detail Screen", profile["knowledge_registry"]["components"])
        self.assertIn("Repository Pattern", profile["knowledge_registry"]["standards"])
        self.assertIn("modules.md", profile["knowledge_registry"]["source_files"])
        self.assertIn("flows.md", profile["source_files"])

    def test_repository_document_analysis_extracts_linedefender_inline_lists(self) -> None:
        documents = {
            "README.md": "LineDefender repository for grid fault monitoring and asset health.",
            "modules.md": "Modules: Authentication, Telemetry, Fault Monitoring, Firmware Management, Asset Health",
            "flows.md": "Flows: Fault Event Review, Outage Investigation, Firmware Upgrade",
            "architecture.md": "Architecture Notes: Backend telemetry APIs publish events to the operations portal.",
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            profile = service.analyze_repository_documents(documents, {"repository_id": "repo-ld", "branch": "main"})

        for module in ["Authentication", "Telemetry", "Fault Monitoring", "Firmware Management", "Asset Health"]:
            self.assertIn(module, profile["knowledge_registry"]["modules"])
        for flow in ["Fault Event Review", "Outage Investigation", "Firmware Upgrade"]:
            self.assertIn(flow, profile["knowledge_registry"]["flows"])
        self.assertIn("Backend telemetry APIs publish events to the operations portal.", profile["knowledge_registry"]["architecture_notes"])

    def test_repository_file_endpoint_shape(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            files = service.repository_files()

        self.assertIn("README.md", files["known_files"])
        self.assertIn("docs/flows.md", files["known_files"])

    def test_project_aware_epic_refinement_avoids_generic_slices(self) -> None:
        profile = {
            "project_name": "LineDefender Smart Monitoring Platform",
            "domain": "Utility Grid Management",
            "project_type": "Multi-System Platform",
            "project_description": "Monitor line devices, telemetry, firmware upgrades and fault events.",
            "applications": [{"name": "Operations Portal", "type": "Web Portal"}, {"name": "Device API", "type": "Backend"}],
            "technology_stack": {"backend": ["FastAPI"], "frontend": ["React"]},
            "knowledge_registry": {
                "modules": ["Telemetry", "Firmware Update", "Fault Event"],
                "flows": ["Device monitoring", "Fault triage", "Firmware rollout"],
            },
            "readme_analysis": {"architecture_notes": ["Backend APIs use repository pattern."]},
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            refined = service.refine_epic({"title": "Improve Device Monitoring", "description": "Improve telemetry, fault and firmware visibility."}, profile)

        feature_titles = [feature["title"] for feature in refined["recommended_features"]]
        self.assertIn("Fault Event Monitoring", feature_titles)
        self.assertIn("Telemetry Health Dashboard", feature_titles)
        self.assertIn("Firmware Upgrade Visibility", feature_titles)
        self.assertFalse(any("Slice" in title or title in {"Story 1", "Story 2"} for title in feature_titles))

    def test_linedefender_feature_generation_uses_detected_fault_modules(self) -> None:
        profile = {
            "project_name": "LineDefender Smart Monitoring Platform",
            "domain": "Utility Grid Management",
            "project_description": "Real-time fault event monitoring with telemetry health.",
            "knowledge_registry": {
                "modules": ["Fault Monitoring", "Telemetry", "Event Repository"],
                "flows": ["Fault Event Review", "Fault Event Timeline", "Device Telemetry Review"],
            },
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            refined = service.refine_epic({"title": "Real-Time Fault Event Monitoring"}, profile)

        titles = [feature["title"] for feature in refined["recommended_features"]]
        self.assertIn("Fault Event Monitoring", titles)
        self.assertIn("Telemetry Health Dashboard", titles)
        self.assertNotIn("Generic Feature", titles)

    def test_feature_story_generation_avoids_generic_fallback_phrases(self) -> None:
        profile = {
            "project_name": "LineDefender Smart Monitoring Platform",
            "domain": "Utility Grid Management",
            "knowledge_registry": {
                "modules": ["Fault Monitoring", "Telemetry"],
                "flows": ["Fault Event Review", "Fault Event Timeline"],
            },
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            refined = service.refine_feature({"title": "Fault Event Monitoring"}, profile)

        story_titles = [story["title"] for story in refined["recommended_stories"]]
        self.assertFalse(any("Configure operating rules" in title for title in story_titles))
        self.assertFalse(any("Validate user outcomes" in title for title in story_titles))
        self.assertIn("provider_used", refined)

    def test_story_refinement_uses_modules_flows_and_considerations(self) -> None:
        profile = {
            "project_name": "LineDefender Smart Monitoring Platform",
            "domain": "Utility Grid Management",
            "project_description": "Device monitoring platform.",
            "applications": [{"name": "Operations Portal", "type": "Web Portal"}],
            "technology_stack": {"backend": ["FastAPI"], "frontend": ["React"]},
            "development_standards": {"testing_requirements": ["Unit tests required"]},
            "ui_guidelines": {"component_library": "LineDefender UI", "accessibility_rules": ["WCAG AA"]},
            "knowledge_registry": {
                "modules": ["Telemetry", "Firmware Update", "Fault Event"],
                "flows": ["Device monitoring", "Fault triage"],
            },
            "readme_analysis": {"architecture_notes": ["Events publish readings to analytics."]},
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            refined = service.refine_story({"title": "View device telemetry health state"}, profile)

        self.assertIn("Operations Portal", refined["affected_applications"])
        self.assertIn("Telemetry", refined["affected_modules"])
        self.assertIn("Device monitoring", refined["affected_flows"])
        self.assertIn("LineDefender UI", " ".join(refined["ui_considerations"]))
        self.assertIn("Unit tests required", refined["qa_considerations"])

    def test_story_impact_identifies_otp_dependencies(self) -> None:
        profile = {
            "project_name": "Customer Access Platform",
            "domain": "Retail",
            "project_type": "Mobile Application",
            "project_description": "Customer mobile app with backend authentication APIs.",
            "applications": [{"name": "Mobile App", "type": "Mobile"}, {"name": "Backend API", "type": "Backend"}],
            "knowledge_registry": {
                "modules": ["Authentication", "Customer Profile"],
                "flows": ["Login", "Token Refresh"],
                "components": ["OTP Entry Screen"],
            },
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            impact = service.analyze_story_impact({"title": "Add OTP Login", "description": "Users verify login with SMS OTP and token refresh."}, profile)

        self.assertIn("Mobile App", impact["affected_applications"])
        self.assertIn("Backend API", impact["affected_applications"])
        self.assertIn("Authentication", impact["affected_modules"])
        self.assertIn("Login", impact["affected_flows"])
        self.assertIn("Auth Service", impact["dependencies"])
        self.assertIn("SMS Provider", impact["dependencies"])
        self.assertIn("Session invalidation", impact["risks"])

    def test_story_impact_uses_linedefender_repository_knowledge(self) -> None:
        profile = {
            "project_name": "LineDefender Smart Monitoring Platform",
            "domain": "Utility Grid Management",
            "project_type": "Multi-System Platform",
            "project_description": "Line device monitoring with telemetry, fault events, and field operations.",
            "applications": [{"name": "Mobile App", "type": "Mobile"}, {"name": "Backend API", "type": "Backend"}],
            "knowledge_registry": {
                "modules": ["Fault Monitoring", "Telemetry", "Event Repository"],
                "flows": ["Fault Event Review", "Telemetry Review"],
                "components": ["Fault Detail Screen", "Event Timeline"],
            },
            "readme_analysis": {"architecture_notes": ["Events publish telemetry to the operations API."]},
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            impact = service.analyze_story_impact({"title": "Display Fault Event Details", "description": "Show large fault history with connectivity-aware telemetry details."}, profile)

        self.assertIn("Mobile App", impact["affected_applications"])
        self.assertIn("Backend API", impact["affected_applications"])
        self.assertIn("Fault Monitoring", impact["affected_modules"])
        self.assertIn("Telemetry", impact["affected_modules"])
        self.assertIn("Fault Event Review", impact["affected_flows"])
        self.assertIn("Event Repository", impact["dependencies"])
        self.assertIn("Telemetry Service", impact["dependencies"])
        self.assertIn("Large event history performance", impact["risks"])
        self.assertIn("Connectivity issues", impact["risks"])

    def test_feature_and_epic_impact_return_domain_specific_dependencies(self) -> None:
        profile = {
            "project_name": "LineDefender Smart Monitoring Platform",
            "domain": "Utility Grid Management",
            "project_description": "Monitor telemetry, faults, and firmware rollout.",
            "applications": [{"name": "Operations Portal", "type": "Web Portal"}, {"name": "Device API", "type": "Backend"}],
            "knowledge_registry": {
                "modules": ["Telemetry", "Firmware Update", "Fault Monitoring"],
                "flows": ["Device monitoring", "Fault Event Review", "Firmware Rollout"],
            },
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            feature_impact = service.analyze_feature_impact({"title": "Fault Event Monitoring"}, profile)
            epic_impact = service.analyze_epic_impact({"title": "Improve Device Monitoring"}, profile)

        self.assertIn("Fault Monitoring", feature_impact["affected_modules"])
        self.assertIn("Fault Event Review", feature_impact["affected_flows"])
        self.assertIn("Coordinate across Backend, Web Portal teams", feature_impact["cross_team_dependencies"])
        self.assertIn("Release planning and stakeholder communication", epic_impact["program_dependencies"])
        self.assertIn("Roll out by device cohort", epic_impact["recommended_rollout_strategy"])

    def test_story_prompts_include_impact_context(self) -> None:
        profile = {
            "project_name": "LineDefender Smart Monitoring Platform",
            "domain": "Utility Grid Management",
            "project_description": "Line device monitoring with fault events.",
            "applications": [{"name": "Mobile App", "type": "Mobile"}, {"name": "Backend API", "type": "Backend"}],
            "technology_stack": {"mobile": ["Kotlin"], "backend": ["FastAPI"]},
            "development_standards": {"testing_requirements": ["Regression tests required"]},
            "knowledge_registry": {
                "modules": ["Fault Monitoring", "Telemetry"],
                "flows": ["Fault Event Review"],
            },
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            prompts = service.generate_story_prompts({"title": "Display Fault Event Details", "acceptance_criteria": ["Fault details are visible."]}, profile)

        self.assertIn("Affected Applications: Mobile App, Backend API", prompts["ui_prompt"])
        self.assertIn("Fault Event Review", prompts["ui_prompt"])
        self.assertIn("Fault Monitoring", prompts["dev_prompt"])
        self.assertIn("Telemetry", prompts["dev_prompt"])
        self.assertIn("Event Repository", prompts["dev_prompt"])
        self.assertIn("Large event history performance", prompts["qa_prompt"])
        self.assertIn("Fault Monitoring API", prompts["qa_prompt"])

    def test_execution_context_builder_uses_project_and_impact_intelligence(self) -> None:
        profile = {
            "project_name": "LineDefender Mobile Platform",
            "domain": "Utility Grid Management",
            "project_type": "Multi-System Platform",
            "project_description": "Hubbell field operations platform for fault event review.",
            "repository_connection": {"status": "README analyzed"},
            "applications": [{"name": "Mobile App", "type": "Mobile"}, {"name": "Backend API", "type": "Backend"}],
            "technology_stack": {"mobile": ["MAUI"], "backend": [".NET"]},
            "development_standards": {
                "architecture_patterns": ["MVVM", "Repository Pattern"],
                "testing_requirements": ["Unit Tests Required"],
            },
            "knowledge_registry": {
                "modules": ["Fault Monitoring", "Telemetry", "Event Repository"],
                "flows": ["Fault Event Review"],
                "components": ["Fault Detail Screen"],
            },
            "readme_analysis": {"architecture_notes": ["Mobile app uses MVVM.", "Backend APIs use Repository Pattern."]},
        }
        story = {
            "title": "Display Fault Event Details",
            "description": "As a field operator, I want to display fault event details.",
            "acceptance_criteria": ["Fault event details are visible from the event list."],
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            context = service.build_execution_context(story, profile)

        self.assertIn("Mobile App", context["affected_applications"])
        self.assertIn("Backend API", context["affected_applications"])
        self.assertIn("Fault Monitoring", context["affected_modules"])
        self.assertIn("Telemetry", context["affected_modules"])
        self.assertIn("Fault Event Review", context["affected_flows"])
        self.assertIn("Telemetry Service", context["dependencies"])
        self.assertIn("Event Repository", context["dependencies"])
        self.assertEqual(context["technology_stack"]["mobile"], ["MAUI"])
        self.assertEqual(context["technology_stack"]["backend"], [".NET"])
        self.assertIn("MVVM", context["development_standards"]["architecture_patterns"])
        self.assertEqual(context["execution_readiness"], "Ready")
        self.assertEqual(context["execution_readiness_result"], "Ready")
        self.assertGreaterEqual(context["execution_readiness_score"], 85)
        self.assertIn("FaultEventViewModel.cs", " ".join(context["recommended_files"]))
        self.assertIn("FaultEventDetailsPage.xaml", " ".join(context["recommended_files"]))
        self.assertIn("FaultEventController.cs", " ".join(context["recommended_files"]))
        self.assertIn("FaultEventRepository.cs", " ".join(context["recommended_files"]))
        self.assertTrue(context["acceptance_criteria_mapping"])
        self.assertTrue(context["implementation_tasks"])
        self.assertTrue(context["testing_tasks"])
        self.assertTrue(context["documentation_tasks"])

    def test_prompt_builders_and_copilot_context_are_project_aware(self) -> None:
        profile = {
            "project_name": "LineDefender Mobile Platform",
            "domain": "Utility Grid Management",
            "project_type": "Multi-System Platform",
            "project_description": "Hubbell field operations platform for fault event review.",
            "repository_connection": {"status": "README analyzed"},
            "applications": [{"name": "Mobile App", "type": "Mobile"}, {"name": "Backend API", "type": "Backend"}],
            "technology_stack": {"mobile": ["MAUI"], "backend": [".NET"]},
            "ui_guidelines": {
                "primary_color": "#004B8D",
                "typography": "Segoe UI",
                "component_library": "Hubbell Mobile UI",
                "accessibility_rules": ["WCAG AA"],
            },
            "development_standards": {
                "architecture_patterns": ["MVVM", "Repository Pattern"],
                "testing_requirements": ["Unit Tests Required"],
            },
            "knowledge_registry": {
                "modules": ["Fault Monitoring", "Telemetry"],
                "flows": ["Fault Event Review"],
            },
            "readme_analysis": {"architecture_notes": ["Mobile app uses MVVM.", "Backend APIs use Repository Pattern."]},
        }
        story = {"title": "Display Fault Event Details", "acceptance_criteria": ["Fault details include timestamp and severity."]}
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            dev_prompt = service.build_dev_prompt(story, profile)["prompt"]
            ui_prompt = service.build_ui_prompt(story, profile)["prompt"]
            qa_prompt = service.build_qa_prompt(story, profile)["prompt"]
            copilot_context = service.build_copilot_context(story, profile)["context"]

        self.assertIn("Technology Stack: mobile: MAUI; backend: .NET", dev_prompt)
        self.assertIn("Coding Standards: MVVM; Repository Pattern; Unit Tests Required", dev_prompt)
        self.assertIn("Architecture Rules: Mobile app uses MVVM., Backend APIs use Repository Pattern.", dev_prompt)
        self.assertIn("Component Library: Hubbell Mobile UI", ui_prompt)
        self.assertIn("Affected User Flows:", ui_prompt)
        self.assertIn("Fault Event Review", ui_prompt)
        self.assertIn("Risks: Large event history performance", qa_prompt)
        self.assertIn("Regression Areas:", qa_prompt)
        self.assertIn("Fault Event Review", qa_prompt)
        self.assertIn("Fault Monitoring", qa_prompt)
        self.assertIn("Project: LineDefender Mobile Platform", copilot_context)
        self.assertIn("Fault Monitoring", copilot_context)
        self.assertIn("Telemetry", copilot_context)
        self.assertIn("Repository Pattern", copilot_context)

    def test_refine_epic_uses_phi_when_healthy_and_enabled(self) -> None:
        provider = HealthyPhiProvider()
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir, "AI_GEN_PROJECT_INTELLIGENCE_USE_PHI": "1"},
            clear=False,
        ), patch("backend.project_intelligence.get_refinement_provider", return_value=provider):
            service = ProjectIntelligenceService()
            refined = service.refine_epic({"title": "Improve Device Monitoring"}, {"project_description": "Fault monitoring platform."})

        self.assertEqual(provider.calls, 1)
        self.assertEqual(refined["provider_used"], "azure_phi")
        self.assertEqual(refined["source"], "azure_phi")
        self.assertEqual(refined["phi_status"], "success")
        self.assertFalse(refined["fallback_used"])
        self.assertEqual(refined["business_goal"], "Phi goal")

    def test_refine_epic_uses_phi_by_default_when_provider_is_healthy(self) -> None:
        provider = HealthyPhiProvider()
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir},
            clear=False,
        ), patch.dict(os.environ, {"AI_GEN_PROJECT_INTELLIGENCE_USE_PHI": ""}, clear=False), patch(
            "backend.project_intelligence.get_refinement_provider",
            return_value=provider,
        ):
            os.environ.pop("AI_GEN_PROJECT_INTELLIGENCE_USE_PHI", None)
            service = ProjectIntelligenceService()
            refined = service.refine_epic({"title": "Improve Device Monitoring"}, {"project_description": "Fault monitoring platform."})

        self.assertEqual(provider.calls, 1)
        self.assertEqual(refined["provider_used"], "azure_phi")
        self.assertEqual(refined["phi_status"], "success")

    def test_project_intelligence_phi_can_be_disabled_explicitly(self) -> None:
        provider = HealthyPhiProvider()
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir, "AI_GEN_PROJECT_INTELLIGENCE_USE_PHI": "0"},
            clear=False,
        ), patch("backend.project_intelligence.get_refinement_provider", return_value=provider):
            service = ProjectIntelligenceService()
            refined = service.refine_epic({"title": "Improve Device Monitoring"}, {"project_description": "Fault monitoring platform."})

        self.assertEqual(provider.calls, 0)
        self.assertEqual(refined["provider_used"], "domain_fallback")
        self.assertEqual(refined["phi_status"], "skipped")
        self.assertIn("disabled", refined["fallback_reason"])

    def test_execution_package_builders_use_phi_when_available(self) -> None:
        provider = HealthyPhiProvider({"prompt": "Phi generated UI prompt"})
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir},
            clear=False,
        ), patch.dict(os.environ, {"AI_GEN_PROJECT_INTELLIGENCE_USE_PHI": ""}, clear=False), patch(
            "backend.project_intelligence.get_refinement_provider",
            return_value=provider,
        ):
            os.environ.pop("AI_GEN_PROJECT_INTELLIGENCE_USE_PHI", None)
            service = ProjectIntelligenceService()
            prompt = service.build_ui_prompt({"title": "Display Fault Event Details"}, {"project_description": "Fault monitoring platform."})

        self.assertGreaterEqual(provider.calls, 1)
        self.assertEqual(prompt["provider_used"], "azure_phi")
        self.assertEqual(prompt["phi_status"], "success")
        self.assertEqual(prompt["prompt"], "Phi generated UI prompt")

    def test_refine_epic_falls_back_when_phi_unhealthy(self) -> None:
        provider = UnhealthyPhiProvider()
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir, "AI_GEN_PROJECT_INTELLIGENCE_USE_PHI": "1"},
            clear=False,
        ), patch("backend.project_intelligence.get_refinement_provider", return_value=provider):
            service = ProjectIntelligenceService()
            refined = service.refine_epic({"title": "Improve Device Monitoring"}, {"project_description": "Fault monitoring platform."})

        self.assertEqual(provider.calls, 0)
        self.assertEqual(refined["provider_used"], "domain_fallback")
        self.assertTrue(refined["fallback_used"])
        self.assertIn("Azure Phi health is unhealthy", refined["fallback_reason"])

    def test_force_phi_failure_is_visible_without_fallback(self) -> None:
        provider = FailingPhiProvider()
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir},
            clear=False,
        ), patch("backend.project_intelligence.get_refinement_provider", return_value=provider):
            service = ProjectIntelligenceService()
            refined = service.refine_epic(
                {"title": "Improve Device Monitoring"},
                {"project_description": "Fault monitoring platform."},
                options={"force_provider": "azure_phi", "allow_fallback": False},
            )

        self.assertEqual(provider.calls, 1)
        self.assertEqual(refined["provider_used"], "azure_phi")
        self.assertFalse(refined["fallback_used"])
        self.assertIn("error", refined)
        self.assertEqual(refined["phi_status"], "provider_timeout")
        self.assertIn("Azure Phi request timed out", refined["fallback_reason"])

    def test_provider_metadata_is_present_on_fallback_outputs(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            service = ProjectIntelligenceService()
            refined = service.refine_story({"title": "Display Fault Event Details"}, {"project_description": "Fault monitoring platform."})
            impact = service.analyze_story_impact({"title": "Display Fault Event Details"}, {"project_description": "Fault monitoring platform."})

        for payload in [refined, impact]:
            self.assertIn("provider_used", payload)
            self.assertIn("source", payload)
            self.assertIn("phi_status", payload)
            self.assertIn("fallback_used", payload)
            self.assertIn("fallback_reason", payload)
            self.assertIn("phi_raw_response_preview", payload)
            self.assertIn("phi_parsed_response_preview", payload)
        self.assertEqual(impact["provider_used"], "deterministic_fallback")

    def test_provider_probe_returns_phi_diagnostics(self) -> None:
        provider = HealthyPhiProvider({"features": ["Fault Monitoring"]})
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir},
            clear=False,
        ), patch("backend.project_intelligence.get_refinement_provider", return_value=provider):
            service = ProjectIntelligenceService()
            result = service.provider_probe(
                "Return project-specific features for LineDefender fault monitoring",
                {"force_provider": "azure_phi"},
            )

        self.assertEqual(result["provider_used"], "azure_phi")
        self.assertEqual(result["phi_status"], "success")
        self.assertEqual(result["parsed_response"], {"features": ["Fault Monitoring"]})
        self.assertEqual(result["latency_ms"], 123)

    def test_project_phi_prompt_compacts_large_knowledge_registry(self) -> None:
        large_profile = {
            "project_name": "LineDefender",
            "domain": "Utility Grid Management",
            "project_type": "Multi-System Platform",
            "project_description": "Project context. " * 400,
            "applications": [{"name": "Mobile App", "type": "Mobile"}],
            "technology_stack": {"mobile": [".NET MAUI"], "backend": ["ASP.NET Core"]},
            "development_standards": {"coding_guidelines": [f"Guideline {index}" for index in range(40)]},
            "ui_guidelines": {"accessibility_rules": [f"UI rule {index}" for index in range(40)]},
            "readme_analysis": {"architecture_notes": ["Architecture note. " * 100 for _ in range(10)]},
            "knowledge_registry": {
                "modules": [f"Module {index}" for index in range(60)],
                "module_details": [
                    {
                        "name": f"Module {index}",
                        "responsibilities": [f"Responsibility {inner}" for inner in range(20)],
                        "dependencies": [f"Dependency {inner}" for inner in range(20)],
                        "source_file": "modules.md",
                    }
                    for index in range(60)
                ],
                "flows": [f"Flow {index}" for index in range(60)],
                "flow_details": [{"name": f"Flow {index}", "steps": [f"Step {inner}" for inner in range(20)]} for index in range(60)],
                "components": [f"Component {index}" for index in range(60)],
                "component_details": [{"name": f"Component {index}", "type": "service"} for index in range(60)],
                "architecture_notes": ["Registry architecture note. " * 100 for _ in range(20)],
                "standards": [f"Standard {index}" for index in range(60)],
                "source_files": [f"docs/file-{index}.md" for index in range(60)],
            },
        }

        prompt = _project_phi_prompt(
            "refine_story",
            large_profile,
            {"title": "Display Fault Event Details"},
            {"story_summary": "Draft", "acceptance_criteria": []},
            ["story_summary", "acceptance_criteria"],
        )

        self.assertLess(len(prompt), 12000)
        self.assertIn("Module 0", prompt)
        self.assertNotIn("Module 40", prompt)
        self.assertNotIn("Responsibility 19", prompt)
        self.assertNotIn("docs/file-40.md", prompt)

    def test_context_budget_manager_summarizes_before_phi(self) -> None:
        large_profile = {
            "project_name": "LineDefender",
            "domain": "Utility Grid Management",
            "project_type": "Multi-System Platform",
            "project_description": "LineDefender monitors grid assets, outage events, telemetry, firmware, and field workflows. " * 180,
            "applications": [{"name": "Mobile App", "type": "Mobile"}, {"name": "Operations Portal", "type": "Web Portal"}],
            "technology_stack": {"mobile": [".NET MAUI"], "backend": ["ASP.NET Core"], "analytics": ["Power BI"]},
            "development_standards": {"coding_guidelines": [f"Guideline {index}" for index in range(60)]},
            "knowledge_registry": {
                "modules": ["Fault Monitoring", "Telemetry", "Firmware Management", *[f"Module {index}" for index in range(80)]],
                "module_details": [
                    {
                        "name": "Fault Monitoring" if index == 0 else f"Module {index}",
                        "responsibilities": [f"Fault event responsibility {inner}" for inner in range(20)],
                        "dependencies": [f"Telemetry dependency {inner}" for inner in range(20)],
                    }
                    for index in range(80)
                ],
                "flows": ["Fault Event Review", "Outage Investigation", *[f"Flow {index}" for index in range(80)]],
                "flow_details": [
                    {
                        "name": "Fault Event Review" if index == 0 else f"Flow {index}",
                        "steps": [f"Review fault event step {inner}" for inner in range(20)],
                    }
                    for index in range(80)
                ],
                "components": [f"Component {index}" for index in range(80)],
                "component_details": [{"name": f"Component {index}", "type": "service"} for index in range(80)],
                "architecture_notes": ["Architecture note for telemetry and fault analysis. " * 120 for _ in range(20)],
                "standards": [f"Standard {index}" for index in range(80)],
                "source_files": [f"docs/file-{index}.md" for index in range(80)],
            },
        }

        prompt, diagnostics = _project_phi_prompt_with_diagnostics(
            "refine_story",
            large_profile,
            {"title": "Display Fault Event Details", "description": "Show telemetry and outage context for a fault event."},
            {"story_summary": "Draft", "acceptance_criteria": []},
            ["story_summary", "acceptance_criteria"],
        )

        self.assertLessEqual(diagnostics["tokens_sent"], 2500)
        self.assertLessEqual(diagnostics["context_after_compression"], diagnostics["context_size"])
        self.assertLessEqual(diagnostics["compression_ratio"], 1)
        self.assertLessEqual(diagnostics["final_prompt_tokens"], diagnostics["model_context_limit"])
        self.assertIn("largest_context_sections", diagnostics)
        self.assertIn("project_summary", prompt)
        self.assertIn("Fault Monitoring", prompt)
        self.assertIn("Fault Event Review", prompt)
        self.assertNotIn("Module 79", prompt)

    def test_project_phi_metadata_includes_context_diagnostics(self) -> None:
        provider = HealthyPhiProvider({"story_summary": "Phi story", "acceptance_criteria": ["AC 1"]})
        profile = {
            "project_description": "Fault monitoring platform.",
            "knowledge_registry": {
                "modules": [f"Module {index}" for index in range(50)],
                "flows": [f"Flow {index}" for index in range(50)],
                "architecture_notes": ["Architecture note. " * 80],
            },
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir, "AI_GEN_PROJECT_INTELLIGENCE_USE_PHI": "1"},
            clear=False,
        ), patch("backend.project_intelligence.get_refinement_provider", return_value=provider):
            refined = ProjectIntelligenceService().refine_story({"title": "Display Fault Event Details"}, profile)

        self.assertEqual(refined["provider_used"], "azure_phi")
        self.assertIn("context_size", refined)
        self.assertIn("context_after_compression", refined)
        self.assertIn("tokens_sent", refined)
        self.assertIn("final_prompt_tokens", refined)
        self.assertIn("largest_context_sections", refined)
        self.assertIn("compression_ratio", refined)
        self.assertLessEqual(refined["tokens_sent"], 2500)

    def test_refine_epic_final_phi_prompt_uses_compressed_context(self) -> None:
        provider = RecordingPhiProvider({"business_goal": "Phi goal", "recommended_features": []})
        profile = {
            "project_description": "LineDefender monitors fault events and telemetry. " * 120,
            "knowledge_registry": {
                "modules": ["Fault Monitoring", *[f"Raw Module {index}" for index in range(80)]],
                "module_details": [
                    {
                        "name": "Fault Monitoring" if index == 0 else f"Raw Module {index}",
                        "responsibilities": [f"Responsibility {inner}" for inner in range(20)],
                        "dependencies": [f"Dependency {inner}" for inner in range(20)],
                    }
                    for index in range(80)
                ],
                "flows": ["Fault Event Review", *[f"Raw Flow {index}" for index in range(80)]],
                "flow_details": [{"name": f"Raw Flow {index}", "steps": [f"Step {inner}" for inner in range(20)]} for index in range(80)],
            },
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir, "AI_GEN_PROJECT_INTELLIGENCE_USE_PHI": "1"},
            clear=False,
        ), patch("backend.project_intelligence.get_refinement_provider", return_value=provider):
            result = ProjectIntelligenceService().refine_epic({"title": "Improve Fault Event Monitoring"}, profile)

        self.assertEqual(provider.calls, 1)
        self.assertLessEqual(len(provider.system_prompt) + len(provider.user_prompt), 4800)
        self.assertIn("Fault Monitoring", provider.user_prompt)
        self.assertNotIn("Raw Module 79", provider.user_prompt)
        self.assertEqual(result["phi_status"], "success")

    def test_build_execution_context_uses_budget_manager(self) -> None:
        provider = RecordingPhiProvider({"story_summary": "Phi execution story", "implementation_tasks": ["Implement fault details"]})
        profile = {
            "project_description": "LineDefender platform. " * 100,
            "knowledge_registry": {
                "modules": ["Fault Monitoring", *[f"Module {index}" for index in range(70)]],
                "flows": ["Fault Event Review", *[f"Flow {index}" for index in range(70)]],
                "architecture_notes": ["Architecture note. " * 100],
            },
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir, "AI_GEN_PROJECT_INTELLIGENCE_USE_PHI": "1"},
            clear=False,
        ), patch("backend.project_intelligence.get_refinement_provider", return_value=provider):
            result = ProjectIntelligenceService().build_execution_context({"title": "Display Fault Event Details"}, profile)

        self.assertEqual(provider.calls, 1)
        self.assertLessEqual(len(provider.system_prompt) + len(provider.user_prompt), 4800)
        self.assertIn("final_prompt_tokens", result)
        self.assertNotEqual(result["phi_status"], "prompt_too_long")

    def test_budget_guard_blocks_before_provider_when_final_prompt_exceeds_limit(self) -> None:
        provider = RecordingPhiProvider({"story_summary": "Should not be called"})
        profile = {
            "project_description": "Fault monitoring platform.",
            "knowledge_registry": {"modules": ["Fault Monitoring"], "flows": ["Fault Event Review"]},
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(
            os.environ,
            {"AI_GEN_DATA_DIR": temp_dir, "AI_GEN_PROJECT_INTELLIGENCE_USE_PHI": "1", "AI_GEN_REFINER_MAX_PROMPT_CHARS": "400"},
            clear=False,
        ), patch("backend.project_intelligence.get_refinement_provider", return_value=provider):
            result = ProjectIntelligenceService().refine_story({"title": "Display Fault Event Details"}, profile)

        self.assertEqual(provider.calls, 0)
        self.assertEqual(result["phi_status"], "blocked_by_budget_guard")
        self.assertEqual(result["prompt_too_long_stage"], "before_provider_call")
        self.assertIn("final_prompt_tokens", result)
        self.assertIn("Largest section", result["fallback_reason"])

    def test_repository_modules_store_responsibilities_and_dependencies_separately(self) -> None:
        documents = {
            "modules.md": """
# Core Modules

## Authentication
### Responsibilities
- Login
- Token management
- Role-based access
### Dependencies
- Identity Provider

## Device Management
### Responsibilities
- Device registration
- Device inventory
- Device lookup
### Dependencies
- Device Repository
""",
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            profile = ProjectIntelligenceService().analyze_repository_documents(documents, {"repository_id": "repo-ld"})

        registry = profile["knowledge_registry"]
        self.assertIn("Authentication", registry["modules"])
        self.assertIn("Device Management", registry["modules"])
        self.assertNotIn("Token management", registry["modules"])
        self.assertNotIn("Identity Provider", registry["modules"])
        auth = next(item for item in registry["module_details"] if item["name"] == "Authentication")
        self.assertIn("Token management", auth["responsibilities"])
        self.assertIn("Identity Provider", auth["dependencies"])

    def test_linedefender_repository_docs_produce_curated_registry(self) -> None:
        documents = {
            "README.md": """
# LineDefender Smart Monitoring Platform
LineDefender is a multi-system utility grid management platform for field mobile workflows, backend APIs, operator dashboards, analytics, and device telemetry integration.
""",
            "modules.md": """
# Core Modules
- Authentication
- Device Management
- Telemetry
- Fault Monitoring
- Firmware Management
- Asset Health
- Reporting
""",
            "flows.md": """
# Operational Flows
- Login Flow
- Device Lookup Flow
- Fault Event Review Flow
- Device Health Review Flow
- Firmware Status Flow
- Outage Investigation Flow
""",
            "architecture.md": """
# Architecture
```text
Mobile | API | Dashboard
```
The LineDefender platform includes a Mobile Application, Backend API, Operations Dashboard, Analytics Platform, Device / Telemetry Integration Layer, Telemetry Communication Layer, Device Services, Telemetry Service, Event Repository, Device Repository, and Device Communication Layer.
It uses .NET MAUI for field mobile workflows, ASP.NET Core REST APIs for device and telemetry services, React/TypeScript for operator dashboards, and Azure/Databricks for analytics.

# Components
- Mobile Application
- Backend API
- Operations Dashboard
- Analytics Platform
- Device / Telemetry Integration Layer
- Telemetry Communication Layer
- Device Services
- Telemetry Service
- Event Repository
- Device Repository
- Device Communication Layer
- Device ID
- Timestamp
""",
            "ui-guidelines.md": """
# UI Guidelines
- Offline-first mobile handling
- High contrast field UI
- 48dp minimum touch target
""",
            "coding-standards.md": """
# Coding Standards
- Role-based access control
- Secure communication
- Audit logging
- Structured logging
- Input validation
- Unit and integration tests
""",
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            profile = ProjectIntelligenceService().analyze_repository_documents(documents, {"repository_id": "repo-ld"})

        registry = profile["knowledge_registry"]
        for module in ["Authentication", "Device Management", "Telemetry", "Fault Monitoring", "Firmware Management", "Asset Health", "Reporting"]:
            self.assertIn(module, registry["modules"])
        for flow in ["Login Flow", "Device Lookup Flow", "Fault Event Review Flow", "Device Health Review Flow", "Firmware Status Flow", "Outage Investigation Flow"]:
            self.assertIn(flow, registry["flows"])
        for component in ["Mobile Application", "Backend API", "Operations Dashboard", "Analytics Platform", "Device / Telemetry Integration Layer", "Telemetry Service", "Event Repository", "Device Repository"]:
            self.assertIn(component, registry["components"])
        self.assertNotIn("Device ID", registry["components"])
        self.assertNotIn("Timestamp", registry["components"])
        self.assertFalse(any("```" in note or "|" in note for note in registry["architecture_notes"]))
        self.assertIn("Role-based access control", registry["standards"])
        self.assertIn("48dp minimum touch target", registry["standards"])
        self.assertIn(profile["knowledge_profile_preview"]["readiness"], ["Intermediate", "Advanced", "Execution Ready"])
        self.assertIn("Role-based access control", profile["development_standards"]["security_requirements"])
        self.assertIn("Unit and integration tests", profile["development_standards"]["testing_requirements"])
        self.assertIn("High contrast field UI", profile["ui_guidelines"]["accessibility_rules"])

    def test_repository_architecture_summary_is_clean(self) -> None:
        documents = {
            "architecture.md": """
# Architecture
```text
App | API | Database
```
Architecture Notes: Backend telemetry APIs publish events to the operations portal.
- Mobile app uses MVVM.
- Backend APIs use Repository Pattern.
""",
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            profile = ProjectIntelligenceService().analyze_repository_documents(documents, {"repository_id": "repo-ld"})

        summary = profile["architecture_summary"]
        self.assertNotIn("```", summary)
        self.assertNotIn("|", summary)
        self.assertIn("Backend telemetry APIs publish events to the operations portal.", profile["knowledge_registry"]["architecture_notes"])

    def test_execution_readiness_requires_repository_modules_flows_and_applications(self) -> None:
        profile = {
            "project_name": "LineDefender",
            "project_description": "Fault monitoring platform.",
            "domain": "Utility Grid Management",
            "project_type": "Multi-System Platform",
            "applications": [{"name": "Mobile Application", "type": "Mobile"}],
            "technology_stack": {"mobile": [".NET MAUI"], "backend": ["ASP.NET Core"]},
            "development_standards": {"coding_guidelines": ["Structured logging"], "security_requirements": [], "testing_requirements": [], "architecture_patterns": []},
            "repository_connection": {"repository_id": "", "repository_name": "", "branch": "", "status": "Not connected"},
            "knowledge_registry": {"modules": ["Fault Monitoring"], "flows": [], "components": [], "architecture_notes": [], "standards": []},
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir}, clear=False):
            context = ProjectIntelligenceService().build_execution_context({"title": "Display Fault Event Details"}, profile, options={"force_provider": "deterministic_fallback"})

        self.assertNotEqual(context["execution_readiness_result"], "Ready")
        self.assertLess(context["execution_readiness_score"], 85)

    def test_feature_generation_returns_richer_fault_event_feature_set(self) -> None:
        profile = {
            "project_description": "LineDefender supports telemetry, fault events, outage investigation, and device health.",
            "knowledge_registry": {
                "modules": ["Fault Monitoring", "Telemetry", "Asset Health", "Firmware Management"],
                "flows": ["Fault Event Review Flow", "Outage Investigation Flow"],
                "components": ["Mobile Application", "Backend API"],
                "architecture_notes": ["Mobile, backend, dashboard, analytics, and telemetry integration layers."],
            },
        }
        with tempfile.TemporaryDirectory() as temp_dir, patch.dict(os.environ, {"AI_GEN_DATA_DIR": temp_dir, "AI_GEN_PROJECT_INTELLIGENCE_USE_PHI": "0"}, clear=False):
            refined = ProjectIntelligenceService().refine_epic({"title": "Improve Fault Event Monitoring", "description": "Improve fault event and outage visibility."}, profile)

        titles = [feature["title"] for feature in refined["recommended_features"]]
        self.assertGreaterEqual(len(titles), 5)
        self.assertIn("Fault Event Timeline", titles)
        self.assertIn("Event Severity Classification", titles)
        self.assertIn("Outage Investigation Support", titles)
        self.assertNotIn("Feature Slice 1", titles)


if __name__ == "__main__":
    unittest.main()
