"""Repository Intelligence foundation module."""

from .application import RepositoryDetectionService, RepositoryIntelligenceApplicationService
from .bootstrap import RepositoryIntelligenceModule, register_repository_intelligence
from .domain import (
    EngineeringGraph,
    EngineeringNode,
    EngineeringNodeType,
    EngineeringRelationship,
    IContextCapsuleBuilder,
    IFileRankingService,
    IEngineeringGraphService,
    IRepositoryParserService,
    IRepositoryScanner,
    IRepositoryService,
    ISnapshotService,
    Repository,
    RepositoryAuthenticationType,
    RepositoryContextCapsule,
    RepositoryFile,
    RepositoryFileRanking,
    RepositoryLanguage,
    RepositoryModule,
    RepositoryParsedSymbol,
    RepositoryScan,
    RepositorySnapshot,
    RepositorySymbolKind,
    RepositoryStatus,
    RepositoryType,
    RelationshipType,
)

__all__ = [
    "EngineeringGraph",
    "EngineeringNode",
    "EngineeringNodeType",
    "EngineeringRelationship",
    "IContextCapsuleBuilder",
    "IEngineeringGraphService",
    "IFileRankingService",
    "IRepositoryParserService",
    "IRepositoryScanner",
    "IRepositoryService",
    "ISnapshotService",
    "Repository",
    "RepositoryAuthenticationType",
    "RepositoryContextCapsule",
    "RepositoryFile",
    "RepositoryFileRanking",
    "RepositoryIntelligenceApplicationService",
    "RepositoryDetectionService",
    "RepositoryIntelligenceModule",
    "RepositoryLanguage",
    "RepositoryModule",
    "RepositoryParsedSymbol",
    "RepositoryScan",
    "RepositorySnapshot",
    "RepositorySymbolKind",
    "RepositoryStatus",
    "RepositoryType",
    "RelationshipType",
    "register_repository_intelligence",
]
